services:

  traefik:
    image: 'traefik:v2.9'
    container_name: traefik
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/traefik.yml
      - ./traefik_dynamic.yml:/traefik_dynamic.yml
      - ./certs:/certs
    networks:
      - web

networks:
  web:
    external: true
