entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "websecure"
          scheme: "https"
  websecure:
    address: ":443"

api:
  dashboard: true
  insecure: false
  debug: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    exposedByDefault: false
    network: "web"
  file:
    fileName: "/traefik_dynamic.yml"
    watch: true

log:
  level: "DEBUG"
