[http.middlewares.simpleAuth.basicAuth]
  users = [
    "docker:$apr1$4CRXX0jL$BGxkdEZ5JKqRAsGJ7NKW1/"
  ]

[http.routers.api]
  rule = "Host(`traefik.nullester.be`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"
